// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulationInsight.ESMData.DAL;

namespace SimulationInsight.ESMData.DAL.Migrations
{
    [DbContext(typeof(ESMContext))]
    [Migration("20210719144346_Migration6")]
    partial class Migration6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MissionNumber")
                        .HasColumnType("int");

                    b.Property<int>("MissionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MissionId");

                    b.ToTable("Mission");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.PulseDescriptor", b =>
                {
                    b.Property<int>("PulseDescriptorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AzimuthAngleDeg")
                        .HasColumnType("float");

                    b.Property<double>("ElevationAngleDeg")
                        .HasColumnType("float");

                    b.Property<double>("FrequencyEnd")
                        .HasColumnType("float");

                    b.Property<double>("FrequencyRampRate")
                        .HasColumnType("float");

                    b.Property<double>("FrequencyStart")
                        .HasColumnType("float");

                    b.Property<double>("PulseModulationType")
                        .HasColumnType("float");

                    b.Property<int>("PulseNumber")
                        .HasColumnType("int");

                    b.Property<double>("PulseTimeEnd")
                        .HasColumnType("float");

                    b.Property<double>("PulseTimeStart")
                        .HasColumnType("float");

                    b.Property<double>("PulseWidth")
                        .HasColumnType("float");

                    b.Property<double>("SignalPower")
                        .HasColumnType("float");

                    b.Property<double>("SignalToNoiseRatio")
                        .HasColumnType("float");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("PulseDescriptorId");

                    b.HasIndex("TrackId");

                    b.ToTable("PulseDescriptor");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.Recording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileName")
                        .HasColumnType("int");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<int>("RecordingNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RecordingId");

                    b.HasIndex("MissionId");

                    b.ToTable("Recording");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrackName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("int");

                    b.HasKey("TrackId");

                    b.HasIndex("MissionId");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.PulseDescriptor", b =>
                {
                    b.HasOne("SimulationInsight.ESMData.Entities.Track", "Track")
                        .WithMany("PulseDescriptors")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.Recording", b =>
                {
                    b.HasOne("SimulationInsight.ESMData.Entities.Mission", "Mission")
                        .WithMany("Recordings")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.Track", b =>
                {
                    b.HasOne("SimulationInsight.ESMData.Entities.Mission", "Mission")
                        .WithMany("Tracks")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.Mission", b =>
                {
                    b.Navigation("Recordings");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SimulationInsight.ESMData.Entities.Track", b =>
                {
                    b.Navigation("PulseDescriptors");
                });
#pragma warning restore 612, 618
        }
    }
}
